//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.16 at 10:05:05 PM CET 
//


package magisterka.SoapBackend.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="textLength" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="textType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="czasWyslaniaRequestuZFrontendu" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="dbmsType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textLength",
    "textType",
    "czasWyslaniaRequestuZFrontendu",
    "dbmsType"
})
@XmlRootElement(name = "getSoapTimes", namespace = "http://www.dupa.pl/soapexample")
public class GetSoapTimes {

    @XmlElement(required = true)
    protected String textLength;
    @XmlElement(required = true)
    protected String textType;
    protected long czasWyslaniaRequestuZFrontendu;
    @XmlElement(required = true)
    protected String dbmsType;

    /**
     * Gets the value of the textLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLength() {
        return textLength;
    }

    /**
     * Sets the value of the textLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLength(String value) {
        this.textLength = value;
    }

    /**
     * Gets the value of the textType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextType() {
        return textType;
    }

    /**
     * Sets the value of the textType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextType(String value) {
        this.textType = value;
    }

    /**
     * Gets the value of the czasWyslaniaRequestuZFrontendu property.
     * 
     */
    public long getCzasWyslaniaRequestuZFrontendu() {
        return czasWyslaniaRequestuZFrontendu;
    }

    /**
     * Sets the value of the czasWyslaniaRequestuZFrontendu property.
     * 
     */
    public void setCzasWyslaniaRequestuZFrontendu(long value) {
        this.czasWyslaniaRequestuZFrontendu = value;
    }

    /**
     * Gets the value of the dbmsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbmsType() {
        return dbmsType;
    }

    /**
     * Sets the value of the dbmsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbmsType(String value) {
        this.dbmsType = value;
    }

}
