//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.16 at 10:05:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dupa.pl/soapexample")
package magisterka.SoapBackend.model;
