//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.16 at 10:05:05 PM CET 
//


package magisterka.SoapBackend.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Times complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Times"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dbDataFetchTime" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="frontToBackEndTime" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="backendResponseTime" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="textsSimilarity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Times", propOrder = {
    "dbDataFetchTime",
    "frontToBackEndTime",
    "backendResponseTime",
    "textsSimilarity"
})
public class Times {

    protected long dbDataFetchTime;
    protected long frontToBackEndTime;
    protected long backendResponseTime;
    protected double textsSimilarity;

    /**
     * Gets the value of the dbDataFetchTime property.
     * 
     */
    public long getDbDataFetchTime() {
        return dbDataFetchTime;
    }

    /**
     * Sets the value of the dbDataFetchTime property.
     * 
     */
    public void setDbDataFetchTime(long value) {
        this.dbDataFetchTime = value;
    }

    /**
     * Gets the value of the frontToBackEndTime property.
     * 
     */
    public long getFrontToBackEndTime() {
        return frontToBackEndTime;
    }

    /**
     * Sets the value of the frontToBackEndTime property.
     * 
     */
    public void setFrontToBackEndTime(long value) {
        this.frontToBackEndTime = value;
    }

    /**
     * Gets the value of the backendResponseTime property.
     * 
     */
    public long getBackendResponseTime() {
        return backendResponseTime;
    }

    /**
     * Sets the value of the backendResponseTime property.
     * 
     */
    public void setBackendResponseTime(long value) {
        this.backendResponseTime = value;
    }

    /**
     * Gets the value of the textsSimilarity property.
     * 
     */
    public double getTextsSimilarity() {
        return textsSimilarity;
    }

    /**
     * Sets the value of the textsSimilarity property.
     * 
     */
    public void setTextsSimilarity(double value) {
        this.textsSimilarity = value;
    }

}
